cut_body_after = "" # don't include text from the PR body in the merge commit message
status = [
  "Evaluate flake.nix",
  "check age-keys [x86_64-linux]",
  "check age-keys-22_11 [x86_64-linux]",
  "check age-ssh-keys [x86_64-linux]",
  "check age-ssh-keys-22_11 [x86_64-linux]",
  "check cross-build-22_11 [x86_64-linux]",
  "check lint-22_11 [x86_64-linux]",
  "check pgp-keys [x86_64-linux]",
  "check pgp-keys-22_11 [x86_64-linux]",
  "check pruning [x86_64-linux]",
  "check pruning-22_11 [x86_64-linux]",
  "check restart-and-reload [x86_64-linux]",
  "check restart-and-reload-22_11 [x86_64-linux]",
  "check sops-init-gpg-key-22_11 [x86_64-linux]",
  "check sops-install-secrets-22_11 [x86_64-linux]",
  "check sops-pgp-hook-test-22_11 [x86_64-linux]",
  "check ssh-keys [x86_64-linux]",
  "check ssh-to-pgp-22_11 [x86_64-linux]",
  "check unit-tests-22_11 [x86_64-linux]",
  "check user-passwords [x86_64-linux]",
  "check user-passwords-22_11 [x86_64-linux]",
  "package cross-build [x86_64-linux]",
  "package lint [x86_64-linux]",
  "package sops-import-keys-hook [x86_64-linux]",
  "package sops-init-gpg-key [x86_64-linux]",
  "package sops-install-secrets [x86_64-linux]",
  "package sops-pgp-hook [x86_64-linux]",
  "package sops-pgp-hook-test [x86_64-linux]",
  "package ssh-to-pgp [x86_64-linux]",
  "package unit-tests [x86_64-linux]",
  "tests"
]
